"""empty message

Revision ID: 7107f09d84d8
Revises: 72d6bb4f0d17
Create Date: 2019-01-03 11:05:07.724146

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7107f09d84d8'
down_revision = '72d6bb4f0d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gname', sa.String(length=50), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('shoppingcart',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('goods_id', sa.Integer(), nullable=True),
                    sa.Column('count', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingcart')
    op.drop_table('goods')
    # ### end Alembic commands ###
