"""empty message

Revision ID: 72d6bb4f0d17
Revises: 2ec513bf3154
Create Date: 2019-01-03 09:59:46.719312

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '72d6bb4f0d17'
down_revision = '2ec513bf3154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_student',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=True),
                    sa.Column('student_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_student')
    # ### end Alembic commands ###
