"""empty message

Revision ID: 2ec513bf3154
Revises: c80d3200518e
Create Date: 2019-01-02 16:31:36.998195

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2ec513bf3154'
down_revision = 'c80d3200518e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wife', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'wife', ['user_id'])
    op.create_foreign_key(None, 'wife', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wife', type_='foreignkey')
    op.drop_constraint(None, 'wife', type_='unique')
    op.drop_column('wife', 'user_id')
    # ### end Alembic commands ###
