"""empty message

Revision ID: c80d3200518e
Revises: 48230b625bc2
Create Date: 2019-01-02 16:14:11.837166

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c80d3200518e'
down_revision = '48230b625bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wife',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('wname', sa.String(length=30), nullable=True),
                    sa.Column('wage', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wife')
    # ### end Alembic commands ###
